version: '{branch}.{build}'
image:
- Visual Studio 2017

clone_folder: c:\gopath\src\github.com\adedayo\tcpscan

environment:
    global:
      GOPATH: C:\gopath
      CC: gcc.exe
    matrix:
      - GETH_ARCH: amd64
        MSYS2_ARCH: x86_64
        MSYS2_BITS: "64"
        MSYSTEM: MINGW64
        PATH: C:\msys64\mingw64\bin\;C:\Program Files (x86)\NSIS\;%PATH%

stack: go 1.11

platform: x64

install:
  - gcc --version
  - cinst winflexbison
  - win_flex --version
  - win_bison --version
  - appveyor DownloadFile https://github.com/the-tcpdump-group/libpcap/archive/libpcap-1.9.0.zip
  - dir
  - 7z x libpcap-1.9.0.zip 
  - move libpcap-libpcap-1.9.0 libpcap
  - cd libpcap
  # - appveyor DownloadFile http://www.winpcap.org/install/bin/WpdPack_4_1_2.zip
  # - 7z x .\WpdPack_4_1_2.zip -oWin32
  # - cd ..
  # - cmake .

build_script:
  - type NUL >.devel
  - md build
  - cd build
  # - cmake -DCMAKE_PREFIX_PATH=..\Win32\WpdPack -G"Visual Studio 12 2013" ..
  # - msbuild -nologo  pcap.sln
  - cmake -DCMAKE_PREFIX_PATH=..\libpcap -G"Visual Studio 15 2017 Win64" ..
  - msbuild /m /nologo /p:Configuration=Release pcap.sln
  - cd ..
  - go get ./...
  - go build github.com\adedayo\tcpscan\cmd\tcpscan


# before_build:
#   - go get ./...
#   - go build github.com\adedayo\tcpscan\cmd\tcpscan

# before_test:
#   - go vet ./...

# test_script:
#   - go test ./...